# Generated by Django 5.2.6 on 2025-11-07 17:09

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/default.jpg', upload_to=users.models.user_directory_path),
        ),
    ]
