# Generated by Django 5.2.6 on 2025-11-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='homecook_status',
            field=models.CharField(choices=[('NONE', 'None'), ('APPROVED', 'Approved')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_homecook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
