# Generated by Django 5.2.6 on 2025-11-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecook',
            name='cuisine',
            field=models.CharField(choices=[('indian', 'Indian'), ('mauritian', 'Mauritian'), ('english', 'English'), ('french', 'French'), ('asian', 'Asian'), ('thai', 'Thai')], max_length=50),
        ),
    ]
