# Generated by Django 5.2.6 on 2025-11-08 11:17

import django.db.models.deletion
import homecook.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecook', '0002_alter_homecook_cuisine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='homecook',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homecook', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homecook',
            name='cuisine',
            field=models.CharField(choices=[('indian', 'Indian'), ('mauritian', 'Mauritian'), ('english', 'English'), ('french', 'French'), ('asian', 'Asian')], max_length=50),
        ),
        migrations.AlterField(
            model_name='homecook',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=homecook.models.homecook_profile_path),
        ),
    ]
