# Generated by Django 5.2.6 on 2026-04-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecook', '0003_homecook_user_alter_homecook_cuisine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecook',
            name='latitude',
            field=models.FloatField(blank=True, default=-20.1609, null=True),
        ),
        migrations.AddField(
            model_name='homecook',
            name='longitude',
            field=models.FloatField(blank=True, default=57.4991, null=True),
        ),
    ]
