"""
Django settings for KiPouCuit project.
Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-krz%!93tw^rlt%ipnu_8b28x5q-spfuwfw7^wv@($krq*z2lb4'
DEBUG = True
ALLOWED_HOSTS = []  # add your domain(s) when deploying
HOMECOOK_ACCESS_CODE = "HOMECOOK2025"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your apps
    'meals',
    'orders',
    'reviews',
    'users',
    'main_page',
    'homecook',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'KiPouCuit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # global templates dir
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Optional but handy for debugging template vars:
                'django.template.context_processors.debug',
                'meals.context_processors.cart_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'KiPouCuit.wsgi.application'

# Database (SQLite for dev)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
#Set to Mauritius time for correct timestamps in admin & templates
TIME_ZONE = 'Indian/Mauritius'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JS, images served from /static/)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",           #keep your project-level static folder
]
# For production you’ll usually add:
# STATIC_ROOT = BASE_DIR / 'staticfiles'

#Media files (user uploads like dish images)
MEDIA_URL = '/media/'               
MEDIA_ROOT = BASE_DIR / 'media'         

#Default PK type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/user_profile/'
LOGOUT_REDIRECT_URL = '/'
